GET http://localhost:3001/exercises

###

POST http://localhost:3001/exercise/new
Content-Type: application/json

{
    "name" : "Pec",
    "sets" : "1 warmup, 3 working",
    "reps" : "8 to failure",
    "notes" : "Slight Shoulder pain, top set 190lbs"
}

###
DELETE http://localhost:3001/exercise/delete/649b50af86e817cb6f4e727c


###
GET http://localhost:3001/workouts

###
POST http://localhost:3001/workout/new
Content-Type: application/json

{
    "date" : "5/1/2023",
    "type" : "Legs",
    "exercises" : [
    {
        "name" : "Squats",
        "sets" : "2 warmup, 3 working",
        "reps" : "8-10 to failure",
        "notes" : "Hip pain during first working set"
    },
    {
        "name" : "Leg Extensions",
        "sets" : "4working",
        "reps" : "8 to failure",
        "notes" : "-"
    },
    {
        "name" : "RDLs with Smith Machine",
        "sets" : "4 working",
        "reps" : "8 to failure",
        "notes" : "Working sets at 225lbs"
    },
    {
        "name" : "Leg Curls",
        "sets" : "4 working",
        "reps" : "AMRAP",
        "notes" : "minimum of 8 per set"
    }
    ]
}